name: inkypanels
options:
  bundleIdPrefix: com.inkypanels
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2" # iPad only

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.15.0

targets:
  inkypanels:
    type: application
    platform: iOS
    sources:
      - path: inkypanels
        excludes:
          - "**/.DS_Store"
    resources:
      - path: inkypanels/Resources
      - path: inkypanels/Preview Content
    settings:
      base:
        INFOPLIST_FILE: inkypanels/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.inkypanels.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: ZIPFoundation

  inkypanelsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: inkypanelsTests
        excludes:
          - "**/.DS_Store"
          - "**/Fixtures/**"
    resources:
      - path: inkypanelsTests/Fixtures
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.inkypanels.tests
    dependencies:
      - target: inkypanels
      - package: SnapshotTesting

schemes:
  inkypanels:
    build:
      targets:
        inkypanels: all
        inkypanelsTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - inkypanelsTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
